### ISSUE TITLE
Resource Handling if path contains whitespace

### ISSUE THREAD

**Issue by alcalda** [KarrLab/unitth#1]
Hello,

on my system the path to the unitth.jar file is
`C:\Program Files\Python36\Lib\site-packages\unitth\lib\unitth\unitth.jar`
 
When I call the run method of class UnitTH, I get an error message 
`subprocess.CalledProcessError: Command 'java -Dunitth.xml.report.filter=TEST- -Dunitth.html.report.path=. -Dunitth.generate.exectimegraphs=true -Dunitth.report.dir=d:\_tmp\unitth\xml\TR-x031.x40_2017-07-26T112800/../../html -jar C:\Program Files\Python36\lib\site-packages\unitth\lib\unitth\unitth.jar d:\_tmp\unitth\xml\TR-x031.x40_2017-07-26T112800/../*' returned non-zero exit status 1.`

When I clone the class and add double quotes around the placeholder for the jar file the function call just runs fine.

Could you please consider this in the next release?

Thanks

**Comment by jonrkarr** [comment]
I added this in 0.0.12. Its pushed to PyPI.

Note, all of our software now requires pip 10.
