### ISSUE TITLE
PyPI package out of date

### ISSUE THREAD

**Issue by joeleong** [KarrLab/unitth#2]
Just a heads up: 

Installing the current PyPI package seems to fail at runtime: 

```
Traceback (most recent call last):
  File "/usr/local/bin/unitth", line 7, in <module>
    from unitth.__main__ import main
  File "/usr/local/lib/python3.6/site-packages/unitth/__main__.py", line 1, in <module>
    from cement.core.foundation import CementApp
```

I assume because the latest changes with support for cement 3 aren't uploaded yet, since installing with the following seems to work:

`pip3 install cement==2.10.12 unitth`

Thanks for the package!

**Comment by jonrkarr** [comment]
Thanks for the reminder. I just pushed the latest version to PyPI.
